In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
 a3.shape

(2, 3, 3)

In [10]:
a1

array([1, 2, 3])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [18]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
ones = np.ones((2, 3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2, 3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[3, 4, 8, 4, 9],
       [7, 3, 5, 1, 1],
       [5, 9, 1, 2, 9]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.24372135, 0.28715475, 0.83228332],
       [0.00138075, 0.70645236, 0.58918306],
       [0.77381643, 0.78723615, 0.62003228],
       [0.42965063, 0.07147768, 0.18431657],
       [0.18040174, 0.6412    , 0.37707324]])

In [31]:
random_array_2.shape

(5, 3)

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.45006611, 0.59030495, 0.35251459],
       [0.49910335, 0.94223435, 0.41066171],
       [0.59152251, 0.93097259, 0.62662143],
       [0.27915219, 0.74331063, 0.76391224],
       [0.62173364, 0.40433234, 0.49879447]])

In [33]:
# Pseudo-random number
np.random.seed(seed=999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 5, 1],
       [8, 1, 9],
       [3, 0, 5],
       [8, 8, 0],
       [5, 2, 5]])

In [34]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [35]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [36]:
random_array_4.shape

(5, 3)

## 3.Viewing Arrays and Matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 2, 3, 5, 8, 9])

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a1[0]

1

In [46]:
a2.shape

(2, 3)

In [47]:
a2[0]

array([1. , 2. , 3.3])

In [48]:
 a3.shape

(2, 3, 3)

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
a2[1]

array([4. , 5. , 6.5])

In [53]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [57]:
a3.shape

(2, 3, 3)

In [54]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [56]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [58]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [62]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4.Manipulating & Comparing Arrays

### Arithmetic

In [63]:
a1

array([1, 2, 3])

In [66]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [67]:
a1 + ones

array([2., 3., 4.])

In [68]:
a1 - ones

array([0., 1., 2.])

In [69]:
a1 * ones

array([1., 2., 3.])

In [70]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [72]:
a1

array([1, 2, 3])

In [71]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [74]:
# To Solve: How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [98]:
a2_n = np.reshape(a2, (1, 6))
a3_n = np.reshape(a3, (3, 6))

In [99]:
a2_n.shape

(1, 6)

In [100]:
a3_n.shape

(3, 6)

In [101]:
a2_n * a3_n

array([[  1. ,   4. ,   9.9,  16. ,  25. ,  39. ],
       [  7. ,  16. ,  29.7,  40. ,  55. ,  78. ],
       [ 13. ,  28. ,  49.5,  64. ,  85. , 117. ]])

In [102]:
a1 / ones

array([1., 2., 3.])

In [104]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [105]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [107]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [106]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [108]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [110]:
a1 + ones

array([2., 3., 4.])

In [109]:
np.add(a1, ones)

array([2., 3., 4.])

In [111]:
a1 % 2

array([1, 0, 1])

In [112]:
a1 / 2

array([0.5, 1. , 1.5])

In [113]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [114]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [115]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
Aggregation = performing the same operation on a number of things

In [116]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [117]:
sum(listy_list)

6

In [118]:
a1

array([1, 2, 3])

In [119]:
type(a1)

numpy.ndarray

In [120]:
sum(a1)

6

In [121]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [122]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [124]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [125]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's np.sum()

19 ms ± 528 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
37.9 µs ± 798 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [126]:
19000 / 37.9

501.3192612137203

In [127]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [128]:
np.mean(a2)

3.6333333333333333

In [129]:
np.max(a2)

6.5

In [130]:
np.min(a2) 

1.0

In [134]:
# Standard deviation = a measure of how spread out a group of number is from the mean
np.std(a2)

1.8226964152656422

In [132]:
# Variance = measure of the average degree to which each number is difference to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [137]:
# Standard Deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422